[package]
name = "filter-expr"
description = "A library for parsing the filter expression."
license = "MIT"
version = "0.1.5"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
regex = "1.12.2"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
